"""initial schema

Revision ID: 2e2f9a44abfb
Revises: 
Create Date: 2026-04-04 12:17:31.543656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2f9a44abfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_transactions',
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('cached_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tx_hash', 'chain')
    )
    op.create_table('historical_prices',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('price_usd', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token', 'date')
    )
    op.create_table('labels',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index('idx_labels_chain_type', 'labels', ['chain', 'entity_type'], unique=False)
    op.create_index('idx_labels_entity', 'labels', ['entity_name'], unique=False)
    op.create_table('method_signatures',
    sa.Column('selector', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('cached_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('selector')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('method_signatures')
    op.drop_index('idx_labels_entity', table_name='labels')
    op.drop_index('idx_labels_chain_type', table_name='labels')
    op.drop_table('labels')
    op.drop_table('historical_prices')
    op.drop_table('cached_transactions')
    # ### end Alembic commands ###
