"""add clusters and risk scores tables

Revision ID: 34159b387fa8
Revises: 2e2f9a44abfb
Create Date: 2026-04-04 16:09:12.937823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34159b387fa8'
down_revision: Union[str, Sequence[str], None] = '2e2f9a44abfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_risk_scores',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.String(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('address', 'chain')
    )
    op.create_table('clusters',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index('idx_cluster', 'clusters', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cluster', table_name='clusters')
    op.drop_table('clusters')
    op.drop_table('cached_risk_scores')
    # ### end Alembic commands ###
